pipeline {
  agent any

  stages {
    stage('Build') {
         steps {
         sh   'npm install'
         sh 'cd ${workspace}/trail/android'
         sh 'echo $PWD'
         sh 'fastlane beta'

        }
   }
 

   stage('Deploy') {
    steps  {
      sh  './jenkins/scripts/deploy.sh'
      echo ' app has been deplloyed successfully'

    }

  }

} 

} 
